sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: I0pjGOa2l7cjscbUTxOBtP8f/nRhssq/umZC+EudS7DqtlCay7k7zAljx2f6eDyxa81/6bYuZ59TM6w+6dnRk43oFXZ7p1BtkyoQ6veA2R45dS2EL7uxiF/PBwWZJyC3yQ5pHrO6uz3+bC029B3liG4vSnbHvRb6muxRMqHwmUuJusTPbEkg25VG4oFtAXN76S+XfjNJXJ6fefq9Dy5jkNX3ckdFsUZLLbONI1cZ8Dyoq5uXU9K+2EXYiUzTTc+4qKvsY7Bp45pcBawD0sa1kAsVtmA9wlGUTUxGMUq/Wz1++2PYattOh+P97aVkNMuLtSxYv24hYp5KvBWk/hA6so4MbrZWNZSad05cn2yw9k/Amh7UB2Tw1JPGd5NtWFVw4QIYO4rOrqsSbP/kJFQ+qaVrXHWKcfgIJXvz1WlwBqJgwanTU8RcVOmR+EJNEcGT0tGGXQXiMbjEWQLY4Cv1f3gAs6x/KchC1lOtCV0TAJSD/Kicugiel2WPdXXYmbyBh0dPqNMSkqyY7DfvyeleR2q5+AOhcwNTbFoq99HFR392bbH6H+A1cwRIVdShzvEZYtV/jCT9VwcXzSGZ12Ap5BKraun4SAnnFNoA87ylyfvvn4vJ5UqyXv/m2zotlEwvf77IfboMLlbHOh26Q1+adb3PVHPYrnWOV9MThbk09fc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Bygone-Beliefs--being-a-series-of-excursions-in-the-byways-of-thought_1271
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy